export type AssetCategory =
  | "people"
  | "family"
  | "animals"
  | "buildings"
  | "vehicles"
  | "nature"
  | "barriers"
  | "food"
  | "household"
  | "spiritual"
  | "military"
  | "objects"
  | "feelings"
  | "fantasy";

export interface SandtrayAsset {
  id: string;
  icon: string;
  label: string;
  category: AssetCategory;
  subcategory?: string;
  mass?: number;
}

export const SANDTRAY_ASSETS: SandtrayAsset[] = [
  // ── People ────────────────────────────────────────────────────────────────
  // Adults
  { id: "person-standing", icon: "🧍", label: "Person Standing", category: "people", subcategory: "Adults" },
  { id: "woman", icon: "👩", label: "Woman", category: "people", subcategory: "Adults" },
  { id: "man", icon: "👨", label: "Man", category: "people", subcategory: "Adults" },
  { id: "person-curly", icon: "🧑‍🦱", label: "Curly Hair", category: "people", subcategory: "Adults" },
  { id: "person-red", icon: "🧑‍🦰", label: "Red Hair", category: "people", subcategory: "Adults" },
  { id: "person-white", icon: "🧑‍🦳", label: "White Hair", category: "people", subcategory: "Adults" },
  { id: "person-bald", icon: "🧑‍🦲", label: "Bald", category: "people", subcategory: "Adults" },
  { id: "pregnant", icon: "🤰", label: "Pregnant", category: "people", subcategory: "Adults" },
  { id: "person-wheelchair", icon: "🧑‍🦽", label: "Wheelchair", category: "people", subcategory: "Adults" },
  { id: "person-cane", icon: "🧑‍🦯", label: "With Cane", category: "people", subcategory: "Adults" },

  // Children
  { id: "child", icon: "🧒", label: "Child", category: "people", subcategory: "Children" },
  { id: "baby", icon: "👶", label: "Baby", category: "people", subcategory: "Children" },
  { id: "girl", icon: "👧", label: "Girl", category: "people", subcategory: "Children" },
  { id: "boy", icon: "👦", label: "Boy", category: "people", subcategory: "Children" },

  // Elders
  { id: "old-woman", icon: "👵", label: "Grandmother", category: "people", subcategory: "Elders" },
  { id: "old-man", icon: "👴", label: "Grandfather", category: "people", subcategory: "Elders" },
  { id: "older-person", icon: "🧓", label: "Older Person", category: "people", subcategory: "Elders" },

  // Professionals
  { id: "doctor", icon: "🧑‍⚕️", label: "Doctor", category: "people", subcategory: "Professionals" },
  { id: "teacher", icon: "🧑‍🏫", label: "Teacher", category: "people", subcategory: "Professionals" },
  { id: "firefighter", icon: "🧑‍🚒", label: "Firefighter", category: "people", subcategory: "Professionals" },
  { id: "pilot", icon: "🧑‍✈️", label: "Pilot", category: "people", subcategory: "Professionals" },
  { id: "farmer", icon: "🧑‍🌾", label: "Farmer", category: "people", subcategory: "Professionals" },
  { id: "cook", icon: "🧑‍🍳", label: "Cook", category: "people", subcategory: "Professionals" },
  { id: "artist", icon: "🧑‍🎨", label: "Artist", category: "people", subcategory: "Professionals" },
  { id: "scientist", icon: "🧑‍🔬", label: "Scientist", category: "people", subcategory: "Professionals" },
  { id: "judge", icon: "🧑‍⚖️", label: "Judge", category: "people", subcategory: "Professionals" },
  { id: "construction", icon: "👷", label: "Construction", category: "people", subcategory: "Professionals" },
  { id: "detective", icon: "🕵️", label: "Detective", category: "people", subcategory: "Professionals" },
  { id: "guard", icon: "💂", label: "Guard", category: "people", subcategory: "Professionals" },
  { id: "police", icon: "👮", label: "Police Officer", category: "people", subcategory: "Professionals" },

  // Royalty & Heroes
  { id: "superhero", icon: "🦸", label: "Superhero", category: "people", subcategory: "Archetypes" },
  { id: "supervillain", icon: "🦹", label: "Supervillain", category: "people", subcategory: "Archetypes" },
  { id: "prince", icon: "🤴", label: "Prince", category: "people", subcategory: "Archetypes" },
  { id: "princess", icon: "👸", label: "Princess", category: "people", subcategory: "Archetypes" },
  { id: "ninja", icon: "🥷", label: "Ninja", category: "people", subcategory: "Archetypes" },

  // ── Family & Relationships ────────────────────────────────────────────────
  { id: "family-mwg", icon: "👨‍👩‍👧", label: "Family (M+W+Girl)", category: "family" },
  { id: "family-mwb", icon: "👨‍👩‍👦", label: "Family (M+W+Boy)", category: "family" },
  { id: "family-mwgb", icon: "👨‍👩‍👧‍👦", label: "Family (4)", category: "family" },
  { id: "family-mwbb", icon: "👨‍👩‍👦‍👦", label: "Family (2 Boys)", category: "family" },
  { id: "family-mwgg", icon: "👨‍👩‍👧‍👧", label: "Family (2 Girls)", category: "family" },
  { id: "family-wg", icon: "👩‍👧", label: "Mom & Daughter", category: "family" },
  { id: "family-wb", icon: "👩‍👦", label: "Mom & Son", category: "family" },
  { id: "family-mg", icon: "👨‍👧", label: "Dad & Daughter", category: "family" },
  { id: "family-mb", icon: "👨‍👦", label: "Dad & Son", category: "family" },
  { id: "couple-m-w", icon: "👫", label: "Couple (M+W)", category: "family" },
  { id: "couple-m-m", icon: "👬", label: "Couple (M+M)", category: "family" },
  { id: "couple-w-w", icon: "👭", label: "Couple (W+W)", category: "family" },
  { id: "couple-heart", icon: "💑", label: "Couple w/ Heart", category: "family" },
  { id: "couple-kiss", icon: "💏", label: "Kiss", category: "family" },
  { id: "handshake", icon: "🤝", label: "Handshake", category: "family" },
  { id: "hug", icon: "🫂", label: "Hug", category: "family" },
  { id: "holding-hands", icon: "🧑‍🤝‍🧑", label: "Holding Hands", category: "family" },

  // ── Animals ───────────────────────────────────────────────────────────────
  // Domestic
  { id: "dog", icon: "🐕", label: "Dog", category: "animals", subcategory: "Domestic" },
  { id: "cat", icon: "🐈", label: "Cat", category: "animals", subcategory: "Domestic" },
  { id: "rabbit", icon: "🐇", label: "Rabbit", category: "animals", subcategory: "Domestic" },
  { id: "hamster", icon: "🐹", label: "Hamster", category: "animals", subcategory: "Domestic" },
  { id: "parrot", icon: "🦜", label: "Parrot", category: "animals", subcategory: "Domestic" },
  { id: "horse", icon: "🐎", label: "Horse", category: "animals", subcategory: "Domestic" },
  { id: "cow", icon: "🐄", label: "Cow", category: "animals", subcategory: "Domestic" },
  { id: "pig", icon: "🐷", label: "Pig", category: "animals", subcategory: "Domestic" },
  { id: "sheep", icon: "🐑", label: "Sheep", category: "animals", subcategory: "Domestic" },
  { id: "rooster", icon: "🐓", label: "Rooster", category: "animals", subcategory: "Domestic" },
  { id: "chick", icon: "🐥", label: "Chick", category: "animals", subcategory: "Domestic" },

  // Wild
  { id: "lion", icon: "🦁", label: "Lion", category: "animals", subcategory: "Wild" },
  { id: "tiger", icon: "🐅", label: "Tiger", category: "animals", subcategory: "Wild" },
  { id: "bear", icon: "🐻", label: "Bear", category: "animals", subcategory: "Wild" },
  { id: "wolf", icon: "🐺", label: "Wolf", category: "animals", subcategory: "Wild" },
  { id: "fox", icon: "🦊", label: "Fox", category: "animals", subcategory: "Wild" },
  { id: "deer", icon: "🦌", label: "Deer", category: "animals", subcategory: "Wild" },
  { id: "elephant", icon: "🐘", label: "Elephant", category: "animals", subcategory: "Wild" },
  { id: "giraffe", icon: "🦒", label: "Giraffe", category: "animals", subcategory: "Wild" },
  { id: "zebra", icon: "🦓", label: "Zebra", category: "animals", subcategory: "Wild" },
  { id: "gorilla", icon: "🦍", label: "Gorilla", category: "animals", subcategory: "Wild" },
  { id: "monkey", icon: "🐒", label: "Monkey", category: "animals", subcategory: "Wild" },
  { id: "panda", icon: "🐼", label: "Panda", category: "animals", subcategory: "Wild" },
  { id: "koala", icon: "🐨", label: "Koala", category: "animals", subcategory: "Wild" },
  { id: "kangaroo", icon: "🦘", label: "Kangaroo", category: "animals", subcategory: "Wild" },
  { id: "hippo", icon: "🦛", label: "Hippo", category: "animals", subcategory: "Wild" },
  { id: "rhino", icon: "🦏", label: "Rhino", category: "animals", subcategory: "Wild" },
  { id: "raccoon", icon: "🦝", label: "Raccoon", category: "animals", subcategory: "Wild" },
  { id: "skunk", icon: "🦨", label: "Skunk", category: "animals", subcategory: "Wild" },
  { id: "hedgehog", icon: "🦔", label: "Hedgehog", category: "animals", subcategory: "Wild" },
  { id: "bat", icon: "🦇", label: "Bat", category: "animals", subcategory: "Wild" },

  // Reptiles & Amphibians
  { id: "snake", icon: "🐍", label: "Snake", category: "animals", subcategory: "Reptiles" },
  { id: "turtle", icon: "🐢", label: "Turtle", category: "animals", subcategory: "Reptiles" },
  { id: "lizard", icon: "🦎", label: "Lizard", category: "animals", subcategory: "Reptiles" },
  { id: "crocodile", icon: "🐊", label: "Crocodile", category: "animals", subcategory: "Reptiles" },
  { id: "frog", icon: "🐸", label: "Frog", category: "animals", subcategory: "Reptiles" },
  { id: "dinosaur", icon: "🦕", label: "Dinosaur", category: "animals", subcategory: "Reptiles" },
  { id: "trex", icon: "🦖", label: "T-Rex", category: "animals", subcategory: "Reptiles" },

  // Birds
  { id: "eagle", icon: "🦅", label: "Eagle", category: "animals", subcategory: "Birds" },
  { id: "owl", icon: "🦉", label: "Owl", category: "animals", subcategory: "Birds" },
  { id: "dove", icon: "🕊️", label: "Dove", category: "animals", subcategory: "Birds" },
  { id: "flamingo", icon: "🦩", label: "Flamingo", category: "animals", subcategory: "Birds" },
  { id: "peacock", icon: "🦚", label: "Peacock", category: "animals", subcategory: "Birds" },
  { id: "swan", icon: "🦢", label: "Swan", category: "animals", subcategory: "Birds" },
  { id: "bird", icon: "🐦", label: "Bird", category: "animals", subcategory: "Birds" },
  { id: "penguin", icon: "🐧", label: "Penguin", category: "animals", subcategory: "Birds" },

  // Sea Creatures
  { id: "fish", icon: "🐟", label: "Fish", category: "animals", subcategory: "Sea" },
  { id: "tropical-fish", icon: "🐠", label: "Tropical Fish", category: "animals", subcategory: "Sea" },
  { id: "whale", icon: "🐋", label: "Whale", category: "animals", subcategory: "Sea" },
  { id: "dolphin", icon: "🐬", label: "Dolphin", category: "animals", subcategory: "Sea" },
  { id: "shark", icon: "🦈", label: "Shark", category: "animals", subcategory: "Sea" },
  { id: "octopus", icon: "🐙", label: "Octopus", category: "animals", subcategory: "Sea" },
  { id: "crab", icon: "🦀", label: "Crab", category: "animals", subcategory: "Sea" },
  { id: "seahorse", icon: "🪸", label: "Coral", category: "animals", subcategory: "Sea" },
  { id: "seal", icon: "🦭", label: "Seal", category: "animals", subcategory: "Sea" },

  // Insects
  { id: "butterfly", icon: "🦋", label: "Butterfly", category: "animals", subcategory: "Insects" },
  { id: "bee", icon: "🐝", label: "Bee", category: "animals", subcategory: "Insects" },
  { id: "ladybug", icon: "🐞", label: "Ladybug", category: "animals", subcategory: "Insects" },
  { id: "ant", icon: "🐜", label: "Ant", category: "animals", subcategory: "Insects" },
  { id: "spider", icon: "🕷️", label: "Spider", category: "animals", subcategory: "Insects" },
  { id: "caterpillar", icon: "🐛", label: "Caterpillar", category: "animals", subcategory: "Insects" },
  { id: "snail", icon: "🐌", label: "Snail", category: "animals", subcategory: "Insects" },
  { id: "worm", icon: "🪱", label: "Worm", category: "animals", subcategory: "Insects" },

  // ── Buildings & Structures ────────────────────────────────────────────────
  { id: "house", icon: "🏠", label: "House", category: "buildings", subcategory: "Homes" },
  { id: "house-garden", icon: "🏡", label: "House & Garden", category: "buildings", subcategory: "Homes" },
  { id: "hut", icon: "🛖", label: "Hut", category: "buildings", subcategory: "Homes" },
  { id: "tent", icon: "⛺", label: "Tent", category: "buildings", subcategory: "Homes" },
  { id: "building", icon: "🏢", label: "Office Building", category: "buildings", subcategory: "Community" },
  { id: "school", icon: "🏫", label: "School", category: "buildings", subcategory: "Community" },
  { id: "hospital", icon: "🏥", label: "Hospital", category: "buildings", subcategory: "Community" },
  { id: "store", icon: "🏪", label: "Store", category: "buildings", subcategory: "Community" },
  { id: "bank", icon: "🏦", label: "Bank", category: "buildings", subcategory: "Community" },
  { id: "factory", icon: "🏭", label: "Factory", category: "buildings", subcategory: "Community" },
  { id: "post-office", icon: "🏤", label: "Post Office", category: "buildings", subcategory: "Community" },
  { id: "church", icon: "⛪", label: "Church", category: "buildings", subcategory: "Sacred" },
  { id: "mosque", icon: "🕌", label: "Mosque", category: "buildings", subcategory: "Sacred" },
  { id: "synagogue", icon: "🕍", label: "Synagogue", category: "buildings", subcategory: "Sacred" },
  { id: "temple", icon: "🛕", label: "Temple", category: "buildings", subcategory: "Sacred" },
  { id: "castle", icon: "🏰", label: "Castle", category: "buildings", subcategory: "Special" },
  { id: "palace", icon: "🏯", label: "Palace", category: "buildings", subcategory: "Special" },
  { id: "lighthouse", icon: "🗼", label: "Tower", category: "buildings", subcategory: "Special" },
  { id: "statue-liberty", icon: "🗽", label: "Statue", category: "buildings", subcategory: "Special" },
  { id: "bridge", icon: "🌉", label: "Bridge", category: "buildings", subcategory: "Structures" },
  { id: "door", icon: "🚪", label: "Door", category: "buildings", subcategory: "Structures" },
  { id: "window", icon: "🪟", label: "Window", category: "buildings", subcategory: "Structures" },
  { id: "ladder", icon: "🪜", label: "Ladder", category: "buildings", subcategory: "Structures" },
  { id: "well", icon: "⛲", label: "Fountain", category: "buildings", subcategory: "Structures" },
  { id: "playground", icon: "🎠", label: "Carousel", category: "buildings", subcategory: "Structures" },
  { id: "ferris-wheel", icon: "🎡", label: "Ferris Wheel", category: "buildings", subcategory: "Structures" },

  // ── Vehicles & Transport ──────────────────────────────────────────────────
  { id: "car", icon: "🚗", label: "Car", category: "vehicles" },
  { id: "truck", icon: "🚚", label: "Truck", category: "vehicles" },
  { id: "bus", icon: "🚌", label: "Bus", category: "vehicles" },
  { id: "ambulance", icon: "🚑", label: "Ambulance", category: "vehicles" },
  { id: "fire-engine", icon: "🚒", label: "Fire Engine", category: "vehicles" },
  { id: "police-car", icon: "🚓", label: "Police Car", category: "vehicles" },
  { id: "taxi", icon: "🚕", label: "Taxi", category: "vehicles" },
  { id: "motorcycle", icon: "🏍️", label: "Motorcycle", category: "vehicles" },
  { id: "bicycle", icon: "🚲", label: "Bicycle", category: "vehicles" },
  { id: "airplane", icon: "✈️", label: "Airplane", category: "vehicles" },
  { id: "helicopter", icon: "🚁", label: "Helicopter", category: "vehicles" },
  { id: "rocket", icon: "🚀", label: "Rocket", category: "vehicles" },
  { id: "sailboat", icon: "⛵", label: "Sailboat", category: "vehicles" },
  { id: "speedboat", icon: "🚤", label: "Speedboat", category: "vehicles" },
  { id: "ship", icon: "🚢", label: "Ship", category: "vehicles" },
  { id: "canoe", icon: "🛶", label: "Canoe", category: "vehicles" },
  { id: "tractor", icon: "🚜", label: "Tractor", category: "vehicles" },
  { id: "train", icon: "🚂", label: "Train", category: "vehicles" },
  { id: "wagon", icon: "🛻", label: "Pickup Truck", category: "vehicles" },
  { id: "sled", icon: "🛷", label: "Sled", category: "vehicles" },

  // ── Nature & Landscape ────────────────────────────────────────────────────
  // Trees & Plants
  { id: "tree-pine", icon: "🌲", label: "Pine Tree", category: "nature", subcategory: "Trees" },
  { id: "tree-deciduous", icon: "🌳", label: "Oak Tree", category: "nature", subcategory: "Trees" },
  { id: "palm-tree", icon: "🌴", label: "Palm Tree", category: "nature", subcategory: "Trees" },
  { id: "cactus", icon: "🌵", label: "Cactus", category: "nature", subcategory: "Trees" },
  { id: "bamboo", icon: "🎋", label: "Bamboo", category: "nature", subcategory: "Trees" },

  // Flowers & Plants
  { id: "flower-cherry", icon: "🌸", label: "Cherry Blossom", category: "nature", subcategory: "Flowers" },
  { id: "sunflower", icon: "🌻", label: "Sunflower", category: "nature", subcategory: "Flowers" },
  { id: "rose", icon: "🌹", label: "Rose", category: "nature", subcategory: "Flowers" },
  { id: "tulip", icon: "🌷", label: "Tulip", category: "nature", subcategory: "Flowers" },
  { id: "hibiscus", icon: "🌺", label: "Hibiscus", category: "nature", subcategory: "Flowers" },
  { id: "bouquet", icon: "💐", label: "Bouquet", category: "nature", subcategory: "Flowers" },
  { id: "shamrock", icon: "☘️", label: "Shamrock", category: "nature", subcategory: "Flowers" },
  { id: "herb", icon: "🌿", label: "Herb", category: "nature", subcategory: "Flowers" },
  { id: "leaf", icon: "🍃", label: "Leaf", category: "nature", subcategory: "Flowers" },
  { id: "mushroom", icon: "🍄", label: "Mushroom", category: "nature", subcategory: "Flowers" },

  // Terrain & Sky
  { id: "mountain", icon: "⛰️", label: "Mountain", category: "nature", subcategory: "Terrain" },
  { id: "volcano", icon: "🌋", label: "Volcano", category: "nature", subcategory: "Terrain" },
  { id: "rock", icon: "🪨", label: "Rock", category: "nature", subcategory: "Terrain" },
  { id: "water-wave", icon: "🌊", label: "Water / Wave", category: "nature", subcategory: "Terrain" },
  { id: "droplet", icon: "💧", label: "Water Drop", category: "nature", subcategory: "Terrain" },
  { id: "snowflake", icon: "❄️", label: "Snowflake", category: "nature", subcategory: "Terrain" },
  { id: "desert", icon: "🏜️", label: "Desert", category: "nature", subcategory: "Terrain" },
  { id: "island", icon: "🏝️", label: "Island", category: "nature", subcategory: "Terrain" },

  // Sky & Weather
  { id: "sun", icon: "☀️", label: "Sun", category: "nature", subcategory: "Sky" },
  { id: "moon-full", icon: "🌕", label: "Full Moon", category: "nature", subcategory: "Sky" },
  { id: "moon-crescent", icon: "🌙", label: "Crescent Moon", category: "nature", subcategory: "Sky" },
  { id: "star-sky", icon: "🌟", label: "Glowing Star", category: "nature", subcategory: "Sky" },
  { id: "cloud", icon: "☁️", label: "Cloud", category: "nature", subcategory: "Sky" },
  { id: "rain", icon: "🌧️", label: "Rain Cloud", category: "nature", subcategory: "Sky" },
  { id: "storm", icon: "⛈️", label: "Storm", category: "nature", subcategory: "Sky" },
  { id: "rainbow", icon: "🌈", label: "Rainbow", category: "nature", subcategory: "Sky" },
  { id: "tornado", icon: "🌪️", label: "Tornado", category: "nature", subcategory: "Sky" },
  { id: "comet", icon: "☄️", label: "Comet", category: "nature", subcategory: "Sky" },

  // ── Barriers & Boundaries ─────────────────────────────────────────────────
  { id: "wall", icon: "🧱", label: "Brick Wall", category: "barriers" },
  { id: "fence-wood", icon: "🏗️", label: "Fence", category: "barriers" },
  { id: "stop-sign", icon: "🛑", label: "Stop Sign", category: "barriers" },
  { id: "no-entry", icon: "⛔", label: "No Entry", category: "barriers" },
  { id: "warning", icon: "⚠️", label: "Warning", category: "barriers" },
  { id: "construction-sign", icon: "🚧", label: "Under Construction", category: "barriers" },
  { id: "lock", icon: "🔒", label: "Lock (Closed)", category: "barriers" },
  { id: "unlock", icon: "🔓", label: "Lock (Open)", category: "barriers" },
  { id: "chain", icon: "⛓️", label: "Chain", category: "barriers" },
  { id: "shield-barrier", icon: "🛡️", label: "Shield", category: "barriers" },
  { id: "road", icon: "🛤️", label: "Railroad / Path", category: "barriers" },
  { id: "crossroads", icon: "🚸", label: "Crossing", category: "barriers" },
  { id: "x-mark", icon: "❌", label: "X Mark", category: "barriers" },
  { id: "prohibited", icon: "🚫", label: "Prohibited", category: "barriers" },

  // ── Food & Nurturing ──────────────────────────────────────────────────────
  { id: "bottle", icon: "🍼", label: "Baby Bottle", category: "food" },
  { id: "breast", icon: "🤱", label: "Nursing", category: "food" },
  { id: "apple", icon: "🍎", label: "Apple", category: "food" },
  { id: "bread", icon: "🍞", label: "Bread", category: "food" },
  { id: "cake", icon: "🎂", label: "Birthday Cake", category: "food" },
  { id: "cookie", icon: "🍪", label: "Cookie", category: "food" },
  { id: "ice-cream", icon: "🍦", label: "Ice Cream", category: "food" },
  { id: "candy", icon: "🍬", label: "Candy", category: "food" },
  { id: "lollipop", icon: "🍭", label: "Lollipop", category: "food" },
  { id: "pizza", icon: "🍕", label: "Pizza", category: "food" },
  { id: "tea", icon: "🍵", label: "Tea Cup", category: "food" },
  { id: "soup", icon: "🍲", label: "Soup / Hot Meal", category: "food" },
  { id: "fruit", icon: "🍇", label: "Grapes", category: "food" },
  { id: "honey", icon: "🍯", label: "Honey", category: "food" },
  { id: "water-glass", icon: "🥛", label: "Milk / Drink", category: "food" },

  // ── Household & Everyday ──────────────────────────────────────────────────
  { id: "bed", icon: "🛏️", label: "Bed", category: "household" },
  { id: "couch", icon: "🛋️", label: "Couch", category: "household" },
  { id: "bathtub", icon: "🛁", label: "Bathtub", category: "household" },
  { id: "toilet", icon: "🚽", label: "Toilet", category: "household" },
  { id: "chair", icon: "🪑", label: "Chair", category: "household" },
  { id: "lamp", icon: "💡", label: "Light / Lamp", category: "household" },
  { id: "clock", icon: "🕐", label: "Clock", category: "household" },
  { id: "phone", icon: "📱", label: "Phone", category: "household" },
  { id: "tv", icon: "📺", label: "Television", category: "household" },
  { id: "computer", icon: "💻", label: "Computer", category: "household" },
  { id: "mirror", icon: "🪞", label: "Mirror", category: "household" },
  { id: "broom", icon: "🧹", label: "Broom", category: "household" },
  { id: "backpack", icon: "🎒", label: "Backpack", category: "household" },
  { id: "umbrella", icon: "☂️", label: "Umbrella", category: "household" },
  { id: "key", icon: "🔑", label: "Key", category: "household" },
  { id: "envelope", icon: "✉️", label: "Letter", category: "household" },
  { id: "camera", icon: "📷", label: "Camera", category: "household" },
  { id: "teddy-bear", icon: "🧸", label: "Teddy Bear", category: "household" },
  { id: "doll", icon: "🪆", label: "Nesting Doll", category: "household" },
  { id: "puzzle", icon: "🧩", label: "Puzzle Piece", category: "household" },
  { id: "balloon", icon: "🎈", label: "Balloon", category: "household" },

  // ── Spiritual & Sacred ────────────────────────────────────────────────────
  { id: "candle", icon: "🕯️", label: "Candle", category: "spiritual" },
  { id: "prayer-beads", icon: "📿", label: "Prayer Beads", category: "spiritual" },
  { id: "yin-yang", icon: "☯️", label: "Yin Yang", category: "spiritual" },
  { id: "om", icon: "🕉️", label: "Om", category: "spiritual" },
  { id: "peace-symbol", icon: "☮️", label: "Peace Symbol", category: "spiritual" },
  { id: "cross", icon: "✝️", label: "Cross", category: "spiritual" },
  { id: "star-david", icon: "✡️", label: "Star of David", category: "spiritual" },
  { id: "crescent-star", icon: "☪️", label: "Crescent & Star", category: "spiritual" },
  { id: "dharma", icon: "☸️", label: "Dharma Wheel", category: "spiritual" },
  { id: "dove-peace", icon: "🕊️", label: "Dove of Peace", category: "spiritual" },
  { id: "lotus", icon: "🪷", label: "Lotus", category: "spiritual" },
  { id: "eye-protection", icon: "🧿", label: "Evil Eye", category: "spiritual" },
  { id: "infinity", icon: "♾️", label: "Infinity", category: "spiritual" },
  { id: "angel-sp", icon: "👼", label: "Angel", category: "spiritual" },

  // ── Military & Conflict ───────────────────────────────────────────────────
  { id: "sword", icon: "⚔️", label: "Swords", category: "military" },
  { id: "bow-arrow", icon: "🏹", label: "Bow & Arrow", category: "military" },
  { id: "bomb", icon: "💣", label: "Bomb", category: "military" },
  { id: "dynamite", icon: "🧨", label: "Firecracker", category: "military" },
  { id: "axe", icon: "🪓", label: "Axe", category: "military" },
  { id: "dagger", icon: "🗡️", label: "Dagger", category: "military" },
  { id: "trident", icon: "🔱", label: "Trident", category: "military" },
  { id: "helmet", icon: "🪖", label: "Military Helmet", category: "military" },
  { id: "skull", icon: "💀", label: "Skull", category: "military" },
  { id: "skull-crossbones", icon: "☠️", label: "Skull & Crossbones", category: "military" },
  { id: "coffin", icon: "⚰️", label: "Coffin", category: "military" },
  { id: "tombstone", icon: "🪦", label: "Tombstone", category: "military" },
  { id: "flag-pirate", icon: "🏴‍☠️", label: "Pirate Flag", category: "military" },
  { id: "flag-white", icon: "🏳️", label: "White Flag", category: "military" },

  // ── Objects & Symbols ─────────────────────────────────────────────────────
  { id: "crown", icon: "👑", label: "Crown", category: "objects" },
  { id: "gem", icon: "💎", label: "Gem", category: "objects" },
  { id: "ring", icon: "💍", label: "Ring", category: "objects" },
  { id: "trophy", icon: "🏆", label: "Trophy", category: "objects" },
  { id: "medal", icon: "🏅", label: "Medal", category: "objects" },
  { id: "gift", icon: "🎁", label: "Gift", category: "objects" },
  { id: "book", icon: "📖", label: "Book", category: "objects" },
  { id: "scroll", icon: "📜", label: "Scroll", category: "objects" },
  { id: "map", icon: "🗺️", label: "World Map", category: "objects" },
  { id: "compass", icon: "🧭", label: "Compass", category: "objects" },
  { id: "hourglass", icon: "⏳", label: "Hourglass", category: "objects" },
  { id: "magnifying", icon: "🔍", label: "Magnifying Glass", category: "objects" },
  { id: "bell", icon: "🔔", label: "Bell", category: "objects" },
  { id: "megaphone", icon: "📢", label: "Megaphone", category: "objects" },
  { id: "speech-bubble", icon: "💬", label: "Speech Bubble", category: "objects" },
  { id: "thought-bubble", icon: "💭", label: "Thought Bubble", category: "objects" },
  { id: "music-note", icon: "🎵", label: "Music", category: "objects" },
  { id: "paint", icon: "🎨", label: "Art Palette", category: "objects" },
  { id: "dice", icon: "🎲", label: "Dice", category: "objects" },
  { id: "magic-wand", icon: "🪄", label: "Magic Wand", category: "objects" },
  { id: "money", icon: "💰", label: "Money Bag", category: "objects" },
  { id: "treasure-chest", icon: "🧳", label: "Treasure Chest", category: "objects" },
  { id: "bandage", icon: "🩹", label: "Bandage", category: "objects" },
  { id: "stethoscope", icon: "🩺", label: "Stethoscope", category: "objects" },
  { id: "pill", icon: "💊", label: "Medicine", category: "objects" },
  { id: "syringe", icon: "💉", label: "Syringe", category: "objects" },

  // ── Feelings & Emotions ───────────────────────────────────────────────────
  // Love & Connection
  { id: "heart-red", icon: "❤️", label: "Love", category: "feelings", subcategory: "Love" },
  { id: "heart-orange", icon: "🧡", label: "Warmth", category: "feelings", subcategory: "Love" },
  { id: "heart-yellow", icon: "💛", label: "Friendship", category: "feelings", subcategory: "Love" },
  { id: "heart-green", icon: "💚", label: "Growth", category: "feelings", subcategory: "Love" },
  { id: "heart-blue", icon: "💙", label: "Trust", category: "feelings", subcategory: "Love" },
  { id: "heart-purple", icon: "💜", label: "Compassion", category: "feelings", subcategory: "Love" },
  { id: "heart-black", icon: "🖤", label: "Grief", category: "feelings", subcategory: "Love" },
  { id: "heart-white", icon: "🤍", label: "Purity", category: "feelings", subcategory: "Love" },
  { id: "heart-broken", icon: "💔", label: "Broken Heart", category: "feelings", subcategory: "Love" },
  { id: "heart-mend", icon: "❤️‍🩹", label: "Mending Heart", category: "feelings", subcategory: "Love" },
  { id: "heart-fire", icon: "❤️‍🔥", label: "Heart on Fire", category: "feelings", subcategory: "Love" },
  { id: "sparkling-heart", icon: "💖", label: "Sparkling Heart", category: "feelings", subcategory: "Love" },

  // Energy & Power
  { id: "fire", icon: "🔥", label: "Fire / Anger", category: "feelings", subcategory: "Energy" },
  { id: "lightning", icon: "⚡", label: "Lightning / Shock", category: "feelings", subcategory: "Energy" },
  { id: "explosion", icon: "💥", label: "Explosion", category: "feelings", subcategory: "Energy" },
  { id: "dizzy", icon: "💫", label: "Dizzy / Confused", category: "feelings", subcategory: "Energy" },
  { id: "sparkle", icon: "✨", label: "Sparkle / Hope", category: "feelings", subcategory: "Energy" },
  { id: "star", icon: "⭐", label: "Star / Achievement", category: "feelings", subcategory: "Energy" },
  { id: "spiral", icon: "🌀", label: "Spiral / Anxiety", category: "feelings", subcategory: "Energy" },
  { id: "100", icon: "💯", label: "100% / Confident", category: "feelings", subcategory: "Energy" },

  // Faces
  { id: "happy", icon: "😊", label: "Happy", category: "feelings", subcategory: "Faces" },
  { id: "joy", icon: "😂", label: "Joy", category: "feelings", subcategory: "Faces" },
  { id: "love-face", icon: "🥰", label: "Loved", category: "feelings", subcategory: "Faces" },
  { id: "cool", icon: "😎", label: "Cool / Confident", category: "feelings", subcategory: "Faces" },
  { id: "thinking", icon: "🤔", label: "Thinking", category: "feelings", subcategory: "Faces" },
  { id: "worried", icon: "😟", label: "Worried", category: "feelings", subcategory: "Faces" },
  { id: "sad", icon: "😢", label: "Sad / Crying", category: "feelings", subcategory: "Faces" },
  { id: "sobbing", icon: "😭", label: "Sobbing", category: "feelings", subcategory: "Faces" },
  { id: "angry", icon: "😠", label: "Angry", category: "feelings", subcategory: "Faces" },
  { id: "furious", icon: "🤬", label: "Furious", category: "feelings", subcategory: "Faces" },
  { id: "scared", icon: "😨", label: "Scared", category: "feelings", subcategory: "Faces" },
  { id: "screaming", icon: "😱", label: "Screaming", category: "feelings", subcategory: "Faces" },
  { id: "disgusted", icon: "🤢", label: "Disgusted", category: "feelings", subcategory: "Faces" },
  { id: "exhausted", icon: "😩", label: "Exhausted", category: "feelings", subcategory: "Faces" },
  { id: "surprised", icon: "😲", label: "Surprised", category: "feelings", subcategory: "Faces" },
  { id: "nervous", icon: "😰", label: "Anxious", category: "feelings", subcategory: "Faces" },
  { id: "confused", icon: "😵‍💫", label: "Confused", category: "feelings", subcategory: "Faces" },
  { id: "sleepy", icon: "😴", label: "Sleepy / Tired", category: "feelings", subcategory: "Faces" },
  { id: "sick", icon: "🤒", label: "Sick", category: "feelings", subcategory: "Faces" },
  { id: "silent", icon: "🤐", label: "Silent / Secrets", category: "feelings", subcategory: "Faces" },
  { id: "shy", icon: "🫣", label: "Shy / Peeking", category: "feelings", subcategory: "Faces" },
  { id: "proud", icon: "🤩", label: "Proud / Amazed", category: "feelings", subcategory: "Faces" },
  { id: "relieved", icon: "😌", label: "Relieved", category: "feelings", subcategory: "Faces" },
  { id: "determined", icon: "😤", label: "Determined", category: "feelings", subcategory: "Faces" },

  // Gestures
  { id: "peace-sign", icon: "✌️", label: "Peace", category: "feelings", subcategory: "Gestures" },
  { id: "thumbs-up", icon: "👍", label: "Thumbs Up", category: "feelings", subcategory: "Gestures" },
  { id: "thumbs-down", icon: "👎", label: "Thumbs Down", category: "feelings", subcategory: "Gestures" },
  { id: "clap", icon: "👏", label: "Clapping", category: "feelings", subcategory: "Gestures" },
  { id: "pray-hands", icon: "🙏", label: "Prayer / Hope", category: "feelings", subcategory: "Gestures" },
  { id: "muscle", icon: "💪", label: "Strength", category: "feelings", subcategory: "Gestures" },
  { id: "raised-fist", icon: "✊", label: "Power / Fight", category: "feelings", subcategory: "Gestures" },
  { id: "open-hands", icon: "🤲", label: "Open Hands", category: "feelings", subcategory: "Gestures" },
  { id: "pointing-up", icon: "☝️", label: "Important", category: "feelings", subcategory: "Gestures" },
  { id: "eyes", icon: "👀", label: "Watching", category: "feelings", subcategory: "Gestures" },
  { id: "brain", icon: "🧠", label: "Brain / Thinking", category: "feelings", subcategory: "Gestures" },

  // ── Fantasy & Mythical ────────────────────────────────────────────────────
  { id: "wizard", icon: "🧙", label: "Wizard", category: "fantasy" },
  { id: "fairy", icon: "🧚", label: "Fairy", category: "fantasy" },
  { id: "elf", icon: "🧝", label: "Elf", category: "fantasy" },
  { id: "genie", icon: "🧞", label: "Genie", category: "fantasy" },
  { id: "troll", icon: "🧌", label: "Troll", category: "fantasy" },
  { id: "mermaid", icon: "🧜", label: "Mermaid", category: "fantasy" },
  { id: "vampire", icon: "🧛", label: "Vampire", category: "fantasy" },
  { id: "zombie", icon: "🧟", label: "Zombie", category: "fantasy" },
  { id: "ghost", icon: "👻", label: "Ghost", category: "fantasy" },
  { id: "alien", icon: "👽", label: "Alien", category: "fantasy" },
  { id: "robot", icon: "🤖", label: "Robot", category: "fantasy" },
  { id: "unicorn", icon: "🦄", label: "Unicorn", category: "fantasy" },
  { id: "dragon", icon: "🐉", label: "Dragon", category: "fantasy" },
  { id: "phoenix", icon: "🐦‍🔥", label: "Phoenix", category: "fantasy" },
  { id: "crystal-ball", icon: "🔮", label: "Crystal Ball", category: "fantasy" },
  { id: "jack-o-lantern", icon: "🎃", label: "Jack-o-Lantern", category: "fantasy" },
  { id: "clown", icon: "🤡", label: "Clown", category: "fantasy" },
  { id: "ogre", icon: "👹", label: "Ogre", category: "fantasy" },
  { id: "goblin", icon: "👺", label: "Goblin", category: "fantasy" },
  { id: "monster", icon: "👾", label: "Monster", category: "fantasy" },
];

export const CATEGORIES: { id: AssetCategory; label: string; emoji: string }[] = [
  { id: "people", label: "People", emoji: "🧑" },
  { id: "family", label: "Family", emoji: "👨‍👩‍👧" },
  { id: "animals", label: "Animals", emoji: "🐾" },
  { id: "buildings", label: "Buildings", emoji: "🏠" },
  { id: "vehicles", label: "Vehicles", emoji: "🚗" },
  { id: "nature", label: "Nature", emoji: "🌿" },
  { id: "barriers", label: "Barriers", emoji: "🧱" },
  { id: "food", label: "Nurturing", emoji: "🍼" },
  { id: "household", label: "Household", emoji: "🏡" },
  { id: "spiritual", label: "Spiritual", emoji: "🕯️" },
  { id: "military", label: "Conflict", emoji: "⚔️" },
  { id: "objects", label: "Objects", emoji: "🔑" },
  { id: "feelings", label: "Feelings", emoji: "💫" },
  { id: "fantasy", label: "Fantasy", emoji: "🧙" },
];
