// VIA Character Strengths - 24 strengths organized under 6 virtues
// Based on Peterson & Seligman's VIA Classification

export interface CharacterStrength {
  id: string;
  name: string;
  emoji: string;
  virtue: string;
  description: string;
  example: string;
  actions: string[];
}

export interface Virtue {
  id: string;
  name: string;
  color: string;
  description: string;
}

export const VIRTUES: Virtue[] = [
  { id: "wisdom", name: "Wisdom", color: "#F59E0B", description: "Cognitive strengths that entail the acquisition and use of knowledge" },
  { id: "courage", name: "Courage", color: "#EF4444", description: "Emotional strengths that involve the exercise of will to accomplish goals in the face of opposition" },
  { id: "humanity", name: "Humanity", color: "#EC4899", description: "Interpersonal strengths that involve tending and befriending others" },
  { id: "justice", name: "Justice", color: "#3B82F6", description: "Civic strengths that underlie healthy community life" },
  { id: "temperance", name: "Temperance", color: "#9CA3AF", description: "Strengths that protect against excess" },
  { id: "transcendence", name: "Transcendence", color: "#8B5CF6", description: "Strengths that forge connections to the larger universe and provide meaning" },
];

export const CHARACTER_STRENGTHS: CharacterStrength[] = [
  { id: "creativity", name: "Creativity", emoji: "🎨", virtue: "wisdom", description: "Thinking of novel and productive ways to do things. Includes artistic achievement but is not limited to it.", example: "Finding a unique solution to a problem no one else thought of, or expressing yourself through art, writing, or play.", actions: ["Try a new way to solve an everyday problem", "Create something — draw, build, write, or invent", "Ask 'what if?' and explore imaginative ideas"] },
  { id: "curiosity", name: "Curiosity", emoji: "🔍", virtue: "wisdom", description: "Taking an interest in ongoing experience for its own sake. Finding subjects and topics fascinating.", example: "Asking lots of questions, wanting to know how things work, or diving deep into a new topic.", actions: ["Ask someone about their favorite thing and really listen", "Explore somewhere new — a trail, a book, a game", "Try something you've never done before this week"] },
  { id: "judgment", name: "Judgment", emoji: "⚖️", virtue: "wisdom", description: "Thinking things through and examining them from all sides. Not jumping to conclusions.", example: "Hearing both sides of an argument before forming an opinion, or pausing to think before making a decision.", actions: ["Before deciding, list pros and cons", "Ask someone with a different perspective to share their view", "Practice saying 'I might be wrong about this'"] },
  { id: "love-of-learning", name: "Love of Learning", emoji: "📚", virtue: "wisdom", description: "Mastering new skills, topics, and bodies of knowledge. A passion for learning new things.", example: "Reading books for fun, taking a class just because it interests you, or teaching yourself a new skill.", actions: ["Learn one new fact today and share it", "Watch a documentary or read about something unfamiliar", "Teach someone else something you know well"] },
  { id: "perspective", name: "Perspective", emoji: "🦉", virtue: "wisdom", description: "Being able to provide wise counsel to others. Having ways of looking at the world that make sense.", example: "Helping a friend see the bigger picture, or knowing when to give advice and when to just listen.", actions: ["Share a lesson you've learned from a tough experience", "Help a friend see a problem from a new angle", "Write a letter of advice to your younger self"] },
  { id: "bravery", name: "Bravery", emoji: "🦁", virtue: "courage", description: "Not shrinking from threat, challenge, difficulty, or pain. Speaking up for what is right.", example: "Standing up for someone being treated unfairly, or trying something scary even though you feel afraid.", actions: ["Do one thing today that feels a little scary", "Stand up for someone or something you believe in", "Share something vulnerable with someone you trust"] },
  { id: "perseverance", name: "Perseverance", emoji: "🏔️", virtue: "courage", description: "Finishing what one starts. Persisting in a course of action in spite of obstacles.", example: "Sticking with a hard project even when you want to quit, or practicing a skill until you get better.", actions: ["Pick one unfinished task and complete it today", "When you want to quit, do five more minutes", "Break a big goal into tiny steps and do the first one"] },
  { id: "honesty", name: "Honesty", emoji: "💎", virtue: "courage", description: "Speaking the truth and presenting oneself in a genuine way. Taking responsibility.", example: "Admitting when you've made a mistake, or being real about how you feel instead of hiding it.", actions: ["Tell someone how you really feel today", "Admit a small mistake without making excuses", "Practice being genuine — skip the 'I'm fine' if you're not"] },
  { id: "zest", name: "Zest", emoji: "⚡", virtue: "courage", description: "Approaching life with excitement and energy. Feeling alive and activated.", example: "Jumping into activities with enthusiasm, bringing energy to a group, or getting excited about everyday moments.", actions: ["Do something physically active that gets your heart pumping", "Approach a routine task with fresh enthusiasm", "Share your excitement about something with someone"] },
  { id: "love", name: "Love", emoji: "❤️", virtue: "humanity", description: "Valuing close relations with others, especially those in which sharing and caring are reciprocated.", example: "Showing warmth to family and friends, giving hugs, or telling someone you care about them.", actions: ["Tell someone important to you why they matter", "Give a genuine hug or write a heartfelt note", "Spend quality time with someone you love"] },
  { id: "kindness", name: "Kindness", emoji: "🤗", virtue: "humanity", description: "Doing favors and good deeds for others. Helping them. Taking care of them.", example: "Helping a classmate with homework, sharing your snack, or cheering someone up when they're sad.", actions: ["Do one random act of kindness today", "Help someone without being asked", "Write an encouraging note and leave it for someone to find"] },
  { id: "social-intelligence", name: "Social Intelligence", emoji: "🎭", virtue: "humanity", description: "Being aware of the motives and feelings of other people and oneself.", example: "Noticing when someone is upset even when they haven't said anything, or knowing how to make people comfortable.", actions: ["Pay extra attention to body language in your next conversation", "Ask someone how they're really doing — and listen closely", "Notice your own emotions and name them throughout the day"] },
  { id: "teamwork", name: "Teamwork", emoji: "🤝", virtue: "justice", description: "Working well as a member of a group or team. Being loyal to the group.", example: "Contributing your part in a group project, supporting your teammates.", actions: ["Volunteer to help with a group task", "Ask a teammate what they need help with", "Celebrate a group win instead of taking individual credit"] },
  { id: "fairness", name: "Fairness", emoji: "🏛️", virtue: "justice", description: "Treating all people the same according to notions of fairness and justice.", example: "Making sure everyone gets a turn, or standing up when rules are applied unfairly.", actions: ["Make sure everyone gets heard in your next group activity", "Question a rule or decision that seems unfair", "Include someone who is being left out"] },
  { id: "leadership", name: "Leadership", emoji: "🌟", virtue: "justice", description: "Encouraging a group to get things done while maintaining good relations.", example: "Organizing a group activity, helping resolve conflicts, or motivating others.", actions: ["Organize a group activity or outing", "Help two people find common ground in a disagreement", "Encourage someone who is struggling"] },
  { id: "forgiveness", name: "Forgiveness", emoji: "🕊️", virtue: "temperance", description: "Forgiving those who have done wrong. Giving people a second chance.", example: "Letting go of a grudge, giving someone another chance, or choosing peace over anger.", actions: ["Let go of one small grudge you're holding", "Write about a time someone hurt you and practice releasing it", "Give someone a second chance this week"] },
  { id: "humility", name: "Humility", emoji: "🌱", virtue: "temperance", description: "Letting one's accomplishments speak for themselves. Not seeking the spotlight.", example: "Not bragging about a win, acknowledging others' contributions.", actions: ["Acknowledge someone else's contribution before your own", "Accept a compliment graciously without deflecting", "Do something helpful without telling anyone about it"] },
  { id: "prudence", name: "Prudence", emoji: "🧭", virtue: "temperance", description: "Being careful about one's choices. Not taking undue risks.", example: "Thinking before you speak, planning ahead, or resisting impulse decisions.", actions: ["Pause for 10 seconds before responding to something upsetting", "Plan tomorrow's schedule tonight", "Think of one possible consequence before making a choice"] },
  { id: "self-regulation", name: "Self-Regulation", emoji: "🧘", virtue: "temperance", description: "Regulating what one feels and does. Being disciplined.", example: "Taking a deep breath instead of yelling, sticking to a routine, or managing screen time.", actions: ["Practice a calming technique when you feel frustrated", "Set a small daily goal and follow through", "Notice an urge and choose to wait before acting on it"] },
  { id: "appreciation-of-beauty", name: "Appreciation of Beauty", emoji: "🌸", virtue: "transcendence", description: "Noticing and appreciating beauty, excellence, and skilled performance.", example: "Stopping to admire a sunset, being moved by music, or appreciating someone's talent.", actions: ["Spend 5 minutes outside noticing something beautiful", "Listen to a piece of music with full attention", "Compliment someone on something they do really well"] },
  { id: "gratitude", name: "Gratitude", emoji: "🙏", virtue: "transcendence", description: "Being aware of and thankful for the good things that happen.", example: "Writing a thank-you note, counting your blessings, or telling someone you appreciate them.", actions: ["Write down three things you're grateful for right now", "Thank someone who made your day better", "Send a gratitude text or note to someone unexpected"] },
  { id: "hope", name: "Hope", emoji: "🌈", virtue: "transcendence", description: "Expecting the best in the future and working to achieve it.", example: "Staying optimistic during hard times, making plans for the future.", actions: ["Write about something you're looking forward to", "When facing a setback, name one thing that could still go right", "Share an encouraging word with someone going through a tough time"] },
  { id: "humor", name: "Humor", emoji: "😄", virtue: "transcendence", description: "Liking to laugh and tease. Bringing smiles to other people. Seeing the light side.", example: "Making your friends laugh, finding the funny side of a bad day, or using humor to lift the mood.", actions: ["Share a joke or funny story with someone today", "Find something to laugh about in a frustrating situation", "Watch or read something that makes you laugh out loud"] },
  { id: "spirituality", name: "Spirituality", emoji: "✨", virtue: "transcendence", description: "Having coherent beliefs about the higher purpose and meaning of life.", example: "Feeling connected to something bigger, finding meaning in everyday moments.", actions: ["Spend 5 quiet minutes reflecting on what gives your life meaning", "Write about a moment that felt deeply meaningful", "Practice being fully present in an ordinary moment"] },
];
