// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-vibes/CoolPrecise.tsx": () => import("../components/mockups/dashboard-vibes/CoolPrecise.tsx"),
  "./components/mockups/dashboard-vibes/SoftEthereal.tsx": () => import("../components/mockups/dashboard-vibes/SoftEthereal.tsx"),
  "./components/mockups/dashboard-vibes/WarmGrounded.tsx": () => import("../components/mockups/dashboard-vibes/WarmGrounded.tsx")
};
